# Generated by Django 3.2.5 on 2021-07-27 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Mobiles & Electronics', 'Mobiles & Electronics'), ('Apparel', 'Apparel'), ('Furniture', 'Furniture'), ('Vehicles & Accessories', 'Vehicles & Accessories'), ('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('Home & Garden', 'Home & Garden')], max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('details', models.CharField(max_length=1000, null=True)),
                ('winner', models.CharField(max_length=200, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Unsold', 'Unsold'), ('Sold', 'Sold')], max_length=200)),
                ('opening_price', models.IntegerField(null=True)),
                ('final_price', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('UPI', 'UPi'), ('Net Banking', 'Net Banking')], max_length=200, null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=200, null=True)),
                ('order_status', models.CharField(choices=[('Processing', 'Processing'), ('Transit', 'Transit'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Processing', max_length=200, null=True)),
                ('created_at', models.DateTimeField()),
                ('auction', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.auction')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('auction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.auction')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='auction',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gt', django.db.models.expressions.F('start_date'))), name='check_start_date'),
        ),
    ]
