# Generated by Django 3.2.5 on 2021-07-27 17:41

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctionimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=auctions.models.generate_filename),
        ),
    ]
