# Generated by Django 3.2.5 on 2021-07-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auctionimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Unsold', 'Unsold'), ('Sold', 'Sold'), ('Ended', 'Ended')], max_length=200),
        ),
    ]
