# Generated by Django 3.2.5 on 2021-08-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_userprofile_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='final_price',
            new_name='buy_price',
        ),
    ]
