# Generated by Django 3.2.5 on 2021-08-03 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_remove_buyrequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
