# Generated by Django 3.2.5 on 2021-08-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_userprofile_stripe_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='stripe_account_id',
            new_name='stripe_user_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_token',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
