# Generated by Django 3.2.5 on 2021-08-06 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20210806_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='access_token',
            new_name='stripe_access_token',
        ),
    ]
