# Generated by Django 3.2.5 on 2021-08-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_rename_access_token_userprofile_stripe_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripe_refresh_token',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
