# Generated by Django 3.2.5 on 2021-08-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_userprofile_stripe_refresh_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_access_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_refresh_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_user_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
