# Generated by Django 3.2.5 on 2021-08-06 17:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_alter_auction_opening_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='shipping_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
