# Generated by Django 3.2.5 on 2021-08-06 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0006_increase_name_max_length'),
        ('auctions', '0028_auto_20210806_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.ForeignKey(blank=True, default='INR', null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.currency'),
        ),
    ]
